---
  - hosts: database
    become: true
    tasks:
      - name: To Install My-Sql Server
        apt: name=mysql-server state=present update_cache=yes
      - name: Ensure Service Enabled
        service: name=mysql state=started enabled=yes
