---
  - hosts: loadbalancer
    become: true
    tasks:
      - name: install NGINX
        apt: name=nginx state=present update_cache=yes
     
      - name: Ensure ngix is running
        service: name=nginx state=started enabled=yes

