---
# Stack Restart

# Stopping Load balancer
- hosts: loadbalancer
  become: true
  tasks:
   - name: STOPPING LOADBALANCER
     service: name=nginx state=stopped

# Stopping Webserver

- hosts: webserver
  become: true
  tasks:
   - name: STOPPING WEBSERVER
     service: name=apache2 state=stopped

# Stopping Database

- hosts: database
  become: true
  tasks:
  - name: STOPPING DATABASE
    service: name=mysql state=stopped

# Starting Database

- hosts: database
  become: true
  tasks:
  - name: STARTING DATABASE
    service: name=mysql state=started enabled=yes

# Starting Webserver

- hosts: webserver
  become: true
  tasks:
  - name: STARTING WEBSERVER
    service: name=apache2 state=started enabled=yes

# Starting load balancer

- hosts: loadbalancer
  become: true
  tasks:
  - name: STRATING LOADBALANCER
    service: name=nginx state=started enabled=yes
