---
- hosts: webserver
  become: true
  tasks:
    - name: Intall Apache2 
      apt: name={{item}} state=present update_cache=yes
      with_items:
         - apache2
         - libapache2-mod-wsgi
         - python-pip
         - python-virtualenv
    - name: Ensure Apache is up and running
      service: name=apache2 state=restarted enabled=yes

